- name: reading variable from file
  hosts: localhost
  become: yes
  gather_facts: no
  vars_friles:
  - variables.yaml
  tasks:
  - name: using loop reading map values
    ansible.builtin.debug:
      msg: "component: {{ item.key }} and {{ item.value }}"
    loop: "{{ softwares | dict2items }}"