- name: Playbook to Read Software Map Variables
  hosts: localhost
  gather_facts: no
  vars:
    softwares:
      catalogs: nodejs
      users: nodejs
      web: nginx
      cart: nodejs
      shipping: maven
      payment: python3-devel
      dispatch: golang

  tasks:
    - name: Display all software components
      debug:
        msg: "Component: {{ item.key }}, Software: {{ item.value }}"
      loop: "{{ softwares | dict2items }}"

    - name: Display specific software
      debug:
        msg: "The software for 'payment' is {{ softwares.payment }}"
